baseURL = "https://dyh0310.github.io/"
locale = "zh-cn"
title = "Your Blog"

theme = "PaperMod"

[params]
  defaultTheme = "dark"
  disableThemeToggle = true
  disableScrollToTop = true
  hideFooter = true
  ShowReadingTime = true
  ShowShareButtons = false
